apiVersion: apps/v1
kind: Deployment
metadata:
  name: ema-api-deployment
  labels:
    app: ema-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ema-api
  template:
    metadata:
      labels:
        app: ema-api
    spec:
      containers:
      - name: ema-api
        image: ema/ema-api
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ema-api-service
  labels:
    app: ema-api
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: ema-api
