version: '3'
services:
  api:
    depends_on:
      - redis
    build: ./
    restart: always
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    links:
      - redis
  redis:
    image: redis:5.0.5-alpine
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
